apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-deployment
  labels:
    name: testapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: testpp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp-conatiner
        image: krishnamohanpandey/testapp:latest
        ports:
        - containerPort: 80
